apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: davmaio-grafana
spec:
  workload:
    apiVersion: core.oam.dev/v1alpha2
    kind: ContainerizedWorkload
    metadata:
      name: davmaio-grafana
    spec:
      osType: linux
      containers:
      - name: davmaio-grafana
        image: grafana/grafana:latest
        imagePullPolicy: IfNotPresent
        resources:
          cpu:
            required: 200m
          memory:
            required: 256Mi
        ports:
          - name: http
            value: 3000
            containerPort: 3000
            type: TCP


        