apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: davmaio-grafana
  annotations:
    version: 0.0.1
    description: "Grafana is the open source analytics & monitoring solution for every database."
spec:
  components:
    - componentName: davmaio-grafana
      traits:
        - trait:
            apiVersion: core.napptive.com/v1alpha1
            kind: Ingress
            metadata:
              name: davmaio-grafana-ingress
            spec:
              name: davmaio-grafana
              protocol: HTTP
              port: 3000
              path: /
              rewritePath: /
        - trait:
            apiVersion: core.oam.dev/v1alpha2
            kind: ManualScalerTrait
            metadata:
              name: davmaio-grafana-trait
            spec:
              replicaCount: 1
      scopes:
        - scopeRef:
            apiVersion: core.oam.dev/v1alpha2
            kind: HealthScope
            name: davmaio-grafana-health